/*
SELECT SH.NAME , P.NAME
 FROM SHIPPERS SH 
  cross JOIN PRODUCTS P
	ORDER BY P.NAME;

 
SELECT SH.NAME , P.NAME
 FROM SHIPPERS SH , PRODUCTS P
	ORDER BY P.NAME;
    */
	SELECT customer_id,FIRST_NAME, POINTS ,  "BRONZE" AS TYPE 
	FROM customers   
		WHERE POINTS < 2000
	UNION		
	SELECT customer_id,FIRST_NAME, POINTS ,  "SILVER" AS TYPE 
	FROM customers   
		WHERE POINTS  between 2000 AND 3000 
    UNION
    SELECT customer_id,FIRST_NAME, POINTS ,  "GOLD" AS TYPE 
	FROM customers   
		WHERE POINTS > 3000
    ORDER BY FIRST_NAME
    