/*
UPDATE CUSTOMERS 

SET POINTS = POINTS + 50
WHERE BIRTH_DATE < "1990-01-01"; 



UPDATE ORDERS 
SET COMMENTS = "GOLD CUSTOMER"
WHERE CUSTOMER_ID IN 
					(SELECT CUSTOMER_ID FROM CUSTOMERS
					WHERE POINTS > 3000)
                    
*/
