/*
INSERT INTO PRODUCTS 
(NAME,QUANTITY_IN_STOCK,UNIT_PRICE)
VALUES("BAG" , 5 , 17),
		("SHAVING MACHINES", 50,10),
        ("NAPKINS",60,18);
        
        
-- INVOICES_ARCHIVE
CREATE TABLE INVOICES_ARCHIVE AS
SELECT I.INVOICE_ID , I.NUMBER,C.NAME,I.INVOICE_TOTAL,I.PAYMENT_TOTAL,I.INVOICE_DATE,I.DUE_DATE,
 I.PAYMENT_DATE
 FROM
INVOICES I
JOIN 
CLIENTS C
USING(CLIENT_ID)
WHERE I.PAYMENT_DATE IS NOT NULL;
*/