
SELECT O.ORDER_ID ,O.ORDER_DATE , C.FIRST_NAME ,SH.NAME AS SHIPPER , OS.NAME AS STATUS
	FROM ORDERS O 
		JOIN CUSTOMERS C 
		ON C.CUSTOMER_ID = O.CUSTOMER_ID
	LEFT JOIN SHIPPERS SH
		ON SH.SHIPPER_ID = O.SHIPPER_ID
	 JOIN order_statuses OS 
		ON OS.order_status_id = O.STATUS;
        
        
        
        SELECT P.DATE ,  C.NAME AS CLIENT , P.AMOUNT,PM.NAME
        FROM PAYMENTS P
        JOIN CLIENTS C
			USING (CLIENT_ID)
		JOIN PAYMENT_METHODS PM
			ON P.PAYMENT_METHOD = PM.PAYMENT_METHOD_ID
            
